#!/bin/bash

export GIT_BITBUCKET_DIR=$(dirname $(realpath "$0"))

usage() {
	echo "usage: git bitbucket <subcommand>"
	echo
	echo "Available subcommands are:"
	echo "    review  Checkout bitbucket pull request to review it locally"
	echo
	echo "Try \`git bitbucket <subcommand> help\` for details"
}

main() {
	if [ $# -lt 1 ]; then
		usage
		exit 1
	fi

	SUBCOMMAND="$1"
	shift

	if [ ! -e "$GIT_BITBUCKET_DIR/git-bitbucket-$SUBCOMMAND" ]; then
		usage
		exit 1
	fi

	. "$GIT_BITBUCKET_DIR/git-bitbucket-$SUBCOMMAND"

	cmd_$SUBCOMMAND "$@"
}

main "$@"
